#!/bin/sh

OS=`uname -s`

if [ $OS = "Linux" ]; then
    echo "\033[44;37;1mBuilding OpenCOR...\033[0m"
fi

cd build

cmake ..
make -j

if [ $OS = "Darwin" ]; then
    # Make sure that OpenCOR can be used on any Mac OS X machine that doesn't
    # have Qt

    macdeployqt OpenCOR.app
fi

cd ..

if [ $OS = "Linux" ]; then
    echo "\033[42;37;1mAll done!\033[0m"
fi
