#!/bin/sh

appDir="$(cd "$(dirname "$0")"; pwd)"

if [ -d "$appDir/build" ]; then
    if [ "`hash ninja 2>&1`" = "" ]; then
        ninjaFound=true
        generator="Ninja"
        cmakeGenerator="Ninja"
    else
        ninjaFound=false
        generator="Make"
        cmakeGenerator="Unix Makefiles"
    fi

    origDir=`pwd`

    $appDir/clean

    echo "\033[44;37;1mBuilding and testing the release version of OpenCOR using $generator...\033[0m"

    cd $appDir/build

    cmake -G "$cmakeGenerator" -DCMAKE_BUILD_TYPE=Release -DENABLE_SAMPLE_PLUGINS=ON -DENABLE_TEST_PLUGINS=ON -DENABLE_TESTS=ON ..

    exitCode=$?

    if [ $exitCode -ne 0 ]; then
        cd $origDir

        exit $exitCode
    fi

    if [ $ninjaFound = true ]; then
        ninja $@

        exitCode=$?
    else
        make $@

        exitCode=$?
    fi

    cd $origDir

    if [ $exitCode -ne 0 ]; then
        exit $exitCode
    fi

    if [ "`uname -s`" = "Linux" ]; then
        appTestsExe=$appDir/build/bin/runtests
    else
        appTestsExe=$appDir/build/OpenCOR.app/Contents/MacOS/runtests
    fi

    $appTestsExe

    exitCode=$?

    if [ $exitCode -eq 0 ]; then
        echo "\033[42;37;1mAll done!\033[0m"
    else
        exit $exitCode
    fi

    $appDir/clean

    echo "\033[44;37;1mBuilding and testing the debug version of OpenCOR using $generator...\033[0m"

    cd $appDir/build

    cmake -G "$cmakeGenerator" -DCMAKE_BUILD_TYPE=Debug -DENABLE_SAMPLE_PLUGINS=ON -DENABLE_TEST_PLUGINS=ON -DENABLE_TESTS=ON ..

    exitCode=$?

    if [ $exitCode -ne 0 ]; then
        cd $origDir

        exit $exitCode
    fi

    if [ $ninjaFound = true ]; then
        ninja $@

        exitCode=$?
    else
        make $@

        exitCode=$?
    fi

    if [ $exitCode -ne 0 ]; then
        cd $origDir

        exit $exitCode
    fi

    $appTestsExe

    exitCode=$?

    cd $origDir

    if [ $exitCode -eq 0 ]; then
        echo "\033[42;37;1mAll done!\033[0m"
    fi

    exit $exitCode
else
    echo "OpenCOR's build directory is missing."

    exit 1
fi
