#!/bin/sh

OS=`uname -s`

if [ $OS = "Linux" ]; then
    echo "\033[44;37;1mCleaning the OpenCOR environment...\033[0m"
fi

rm -fr build/_CPack_Packages/* build/CMakeFiles/* build/src/* > /dev/null 2>&1
rm -f build/* > /dev/null 2>&1
rmdir build/_CPack_Packages build/CMakeFiles build/src > /dev/null 2>&1

if [ $OS != "Linux" ]; then
    rm -fr build/lib/* build/OpenCOR.app/* > /dev/null 2>&1
    rmdir build/lib build/OpenCOR.app > /dev/null 2>&1
fi

if [ $OS = "Linux" ]; then
    echo "\033[42;37;1mAll done!\033[0m"
fi
