#!/bin/sh

OS=`uname -s`

if [ $OS = "Linux" ]; then
    echo "\033[44;37;1mCleaning the OpenCOR environment...\033[0m"
fi

cd build

if [ -f Makefile ]; then
    make -j clean
fi

rm -fr 3rdparty *ake* _CPack_Packages install_manifest.txt *OpenCOR* src

cd ..

if [ $OS = "Linux" ]; then
    echo "\033[42;37;1mAll done!\033[0m"
fi
