#!/bin/sh

./clean

export PACKAGE_OPENCOR=True

./make $*

exitCode=$?

if [ $exitCode -ne 0 ]; then
    exit $exitCode
fi

echo "\033[44;37;1mPackaging OpenCOR...\033[0m"

cd build

cpack -C CPackConfig.cmake

exitCode=$?

cd ..

if [ $exitCode -eq 0 ]; then
    echo "\033[42;37;1mAll done!\033[0m"
fi

exit $exitCode
