#!/bin/sh

./clean
./make $*

exitCode=$?

if [ $exitCode -ne 0 ]; then
    exit $exitCode
fi

echo "\033[44;37;1mPackaging OpenCOR...\033[0m"

cd build

if [ "`uname -s`" = "Linux" ]; then
    cpack
else
    cpack -G PackageMaker -D CPACK_INSTALL_PREFIX=/Applications/OpenCOR
    cpack -G ZIP -D CPACK_INSTALL_PREFIX=.
fi

exitCode=$?

cd ..

if [ $exitCode -eq 0 ]; then
    echo "\033[42;37;1mAll done!\033[0m"
fi

exit $exitCode
