#!/bin/sh

./cleanprojall
./makeproj

OS=`uname -s`

if [ $OS = "Linux" ]; then
    echo "\033[44;37;1mPackaging OpenCOR...\033[0m"
fi

cd build

cpack

cd ..

if [ $OS = "Linux" ]; then
    echo "\033[42;37;1mAll done!\033[0m"
fi
