#!/bin/bash

appDir=$(cd $(dirname $0); pwd)

$appDir/clean
$appDir/make "$@"

exitCode=$?

if [ $exitCode -ne 0 ]; then
    exit $exitCode
fi

echo -e "\033[44;37;1mPackaging OpenCOR...\033[0m"

origDir=`pwd`

cd $appDir/build

cpack

exitCode=$?

cd $origDir

if [ $exitCode -eq 0 ]; then
    echo -e "\033[42;37;1mAll done!\033[0m"
fi

exit $exitCode
