#!/bin/sh

echo "\033[44;37;1mRunning OpenCOR...\033[0m"

crtDir="$(cd "$(dirname "$0")"; pwd)"

if [ "`uname -s`" = "Linux" ]; then
    appExe=${crtDir}/build/bin/OpenCOR
else
    appExe=${crtDir}/build/OpenCOR.app/Contents/MacOS/OpenCOR
fi

if [ -f ${appExe} ]; then
    ${appExe} "$@"
else
    echo "OpenCOR must first be built before being run."
fi

echo "\033[42;37;1mAll done!\033[0m"
