#!/bin/sh

OS=`uname -s`

if [ $OS = "Linux" ]
then
   echo "\033[44;37;1mRunning OpenCOR...\033[0m"
fi

if [ $OS = "Linux" ]
then
   build/OpenCOR
fi

if [ $OS = "Linux" ]
then
   echo "\033[42;37;1mAll done!\033[0m"
fi

