#!/bin/sh

echo "\033[44;37;1mRunning OpenCOR's tests...\033[0m"

appDir="$(cd "$(dirname "$0")"; pwd)"

if [ "`uname -s`" = "Linux" ]; then
    OPENCOR_TESTS_EXE=${appDir}/build/bin/runtests
else
    OPENCOR_TESTS_EXE=${appDir}/build/OpenCOR.app/Contents/MacOS/runtests
fi

if [ -f ${OPENCOR_TESTS_EXE} ]; then
    ${OPENCOR_TESTS_EXE} "$@"
else
    echo "OpenCOR's tests must first be built before being run."
fi

echo "\033[42;37;1mAll done!\033[0m"
