#!/bin/sh

echo "\033[44;37;1mRunning OpenCOR's tests...\033[0m"

if [ -f build/tests/runtests ]; then
    build/tests/runtests
else
    echo "OpenCOR's tests must first be built before being run."
fi

echo "\033[42;37;1mAll done!\033[0m"
