<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="fr_FR" sourcelanguage="en_GB">
<context>
    <name>BioSignalMLSaveDialog</name>
    <message>
        <source>Save results to BioSignalML</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>BioSignalML file:</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Short name:</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Description:</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Author:</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Set name</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Exported Variables:</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>All variables</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Select</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>&lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0//EN&quot; &quot;http://www.w3.org/TR/REC-html40/strict.dtd&quot;&gt;
&lt;html&gt;&lt;head&gt;&lt;meta name=&quot;qrichtext&quot; content=&quot;1&quot; /&gt;&lt;style type=&quot;text/css&quot;&gt;
p, li { white-space: pre-wrap; }
&lt;/style&gt;&lt;/head&gt;&lt;body style=&quot; font-family:&apos;.SF NS Text&apos;; font-size:13pt; font-weight:400; font-style:normal;&quot;&gt;
&lt;p style=&quot;-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:&apos;.Helvetica Neue DeskInterface&apos;;&quot;&gt;&lt;br /&gt;&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>BioSignalMLSelectVariables</name>
    <message>
        <source>All variables</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Export</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Select variables to export</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>QObject</name>
    <message>
        <source>Enter BioSignalML file name</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Generated by</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>at</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>from</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>All variables</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>No variables</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>As specified</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>BioSignalML File</source>
        <translation type="unfinished"></translation>
    </message>
</context>
</TS>
