<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="fr_FR" sourcelanguage="en_GB">
<context>
    <name>OpenCOR::BioSignalMLDataStore::BioSignalMLDataStorePlugin</name>
    <message>
        <source>BioSignalML File</source>
        <translation>Fichier BioSignalML</translation>
    </message>
    <message>
        <source>Export To BioSignalML</source>
        <translation>Exporter Vers BioSignalML</translation>
    </message>
    <message>
        <source>Data</source>
        <translation>Données</translation>
    </message>
    <message>
        <source>Generated by %1 at %2 from %3.</source>
        <translation>Généré par %1 à %2 à partir de %3.</translation>
    </message>
</context>
<context>
    <name>OpenCOR::BioSignalMLDataStore::BiosignalmlDataStoreDialog</name>
    <message>
        <source>Export Data</source>
        <translation>Données D&apos;Export</translation>
    </message>
    <message>
        <source>Name:</source>
        <translation>Nom :</translation>
    </message>
    <message>
        <source>Author:</source>
        <translation>Auteur :</translation>
    </message>
    <message>
        <source>Description:</source>
        <translation>Description :</translation>
    </message>
</context>
<context>
    <name>OpenCOR::BioSignalMLDataStore::BiosignalmlDataStoreExporterWorker</name>
    <message>
        <source>The data could not be exported to BioSignalML (%1).</source>
        <translation>Les données n&apos;ont pas pu être exportées vers BioSignalML (%1).</translation>
    </message>
</context>
</TS>
