/* This file is automatically generated from DOM_events.idl
 * DO NOT EDIT DIRECTLY OR CHANGES WILL BE LOST!
 */
#ifndef _GUARD_IFACE_DOMevents
#define _GUARD_IFACE_DOMevents
#include "cda_compiler_support.h"
#ifdef MODULE_CONTAINS_DOMevents
#define PUBLIC_DOMevents_PRE CDA_EXPORT_PRE
#define PUBLIC_DOMevents_POST CDA_EXPORT_POST
#else
#define PUBLIC_DOMevents_PRE CDA_IMPORT_PRE
#define PUBLIC_DOMevents_POST CDA_IMPORT_POST
#endif
#include "Ifacexpcom.hxx"
#include "IfaceDOM_APISPEC.hxx"
namespace iface
{
  namespace events
  {
    typedef wchar_t* DOMString;
    typedef uint64_t DOMTimeStamp;
    typedef iface::dom::Node* Node;
    class EventListener;
    class Event;
    PUBLIC_DOMevents_PRE 
    class  PUBLIC_DOMevents_POST EventException : public std::exception
    {
    public:
      EventException(){}
    };
    static const uint16_t UNSPECIFIED_EVENT_TYPE_ERR = 0;
    PUBLIC_DOMevents_PRE 
    class  PUBLIC_DOMevents_POST EventTarget
     : public virtual iface::XPCOM::IObject
    {
    public:
      virtual ~EventTarget() {}
      virtual void addEventListener(const wchar_t* type, iface::events::EventListener* listener, bool useCapture) throw(std::exception&) = 0;
      virtual void removeEventListener(const wchar_t* type, iface::events::EventListener* listener, bool useCapture) throw(std::exception&) = 0;
      virtual bool dispatchEvent(iface::events::Event* evt) throw(std::exception&) = 0;
    };
    PUBLIC_DOMevents_PRE 
    class  PUBLIC_DOMevents_POST EventListener
     : public virtual iface::XPCOM::IObject
    {
    public:
      virtual ~EventListener() {}
      virtual void handleEvent(iface::events::Event* evt) throw(std::exception&) = 0;
    };
    PUBLIC_DOMevents_PRE 
    class  PUBLIC_DOMevents_POST Event
     : public virtual iface::XPCOM::IObject
    {
    public:
      virtual ~Event() {}
      static const uint16_t CAPTURING_PHASE = 1;
      static const uint16_t AT_TARGET = 2;
      static const uint16_t BUBBLING_PHASE = 3;
      virtual wchar_t* type() throw(std::exception&)  WARN_IF_RETURN_UNUSED = 0;
      virtual iface::events::EventTarget* target() throw(std::exception&)  WARN_IF_RETURN_UNUSED = 0;
      virtual iface::events::EventTarget* currentTarget() throw(std::exception&)  WARN_IF_RETURN_UNUSED = 0;
      virtual uint16_t eventPhase() throw(std::exception&)  = 0;
      virtual bool bubbles() throw(std::exception&)  = 0;
      virtual bool cancelable() throw(std::exception&)  = 0;
      virtual uint64_t timeStamp() throw(std::exception&)  = 0;
      virtual void stopPropagation() throw(std::exception&) = 0;
      virtual void preventDefault() throw(std::exception&) = 0;
      virtual void initEvent(const wchar_t* eventTypeArg, bool canBubbleArg, bool cancelableArg) throw(std::exception&) = 0;
    };
    PUBLIC_DOMevents_PRE 
    class  PUBLIC_DOMevents_POST DocumentEvent
     : public virtual iface::XPCOM::IObject
    {
    public:
      virtual ~DocumentEvent() {}
      virtual iface::events::Event* createEvent(const wchar_t* domEventType) throw(std::exception&) WARN_IF_RETURN_UNUSED = 0;
    };
    PUBLIC_DOMevents_PRE 
    class  PUBLIC_DOMevents_POST MutationEvent
     : public virtual iface::events::Event
    {
    public:
      virtual ~MutationEvent() {}
      static const uint16_t MODIFICATION = 1;
      static const uint16_t ADDITION = 2;
      static const uint16_t REMOVAL = 3;
      virtual iface::dom::Node* relatedNode() throw(std::exception&)  WARN_IF_RETURN_UNUSED = 0;
      virtual wchar_t* prevValue() throw(std::exception&)  WARN_IF_RETURN_UNUSED = 0;
      virtual wchar_t* newValue() throw(std::exception&)  WARN_IF_RETURN_UNUSED = 0;
      virtual wchar_t* attrName() throw(std::exception&)  WARN_IF_RETURN_UNUSED = 0;
      virtual uint16_t attrChange() throw(std::exception&)  = 0;
      virtual void initMutationEvent(const wchar_t* typeArg, bool canBubbleArg, bool cancelableArg, iface::dom::Node* relatedNodeArg, const wchar_t* prevValueArg, const wchar_t* newValueArg, const wchar_t* attrNameArg, uint16_t attrChangeArg) throw(std::exception&) = 0;
    };
  };
};
#undef PUBLIC_DOMevents_PRE
#undef PUBLIC_DOMevents_POST
#endif // guard
