#!/bin/sh

QT_LIBRARY_PATH=`which qmake | sed -e 's/bin\/qmake/lib/' -e 's/\//\\\\\//g'`

if [ $# -le 1 ]; then
    if [ $# -eq 1 ]; then
        if [ -d $1 ]; then
            cd $1

            FILES=.
        else
            FILES=$1
        fi
    else
        FILES=.
    fi

    otool -L `du -a $FILES | awk '{ print $2 }'` 2> /dev/null | grep "	$QT_LIBRARY_PATH" | sed -e 's/^.*'$QT_LIBRARY_PATH'\///' -e 's/^.*\.framework\/Versions\/5\///' -e 's/ .*$//' | sort -u
else
    echo "Usage: `basename $0` [<FileNameOrFolderName>]"
fi

