#!/bin/sh

crtDir="$(cd "$(dirname "$0")"; pwd)"

export PATH="${crtDir}/bin":$PATH

"${crtDir}/python/bin/python" "${crtDir}/python/bin/set_python_path.py" "${crtDir}/python" -s

"${crtDir}/python/bin/jupyter" $*
