#!/bin/sh

homeDir="$(cd "$(dirname "$0")"; pwd)/../.."

export PATH="${homeDir}/bin":$PATH

"${homeDir}/python/bin/python" "${homeDir}/python/bin/set_python_path.py" "${homeDir}/python" -s

"${homeDir}/python/bin/jupyter" $*
