#!/bin/sh

cmakeBuildType=$1

if [ "$cmakeBuildType" = "Release" ]; then
    enableTests=OFF
else
    cmakeBuildType=Debug
    enableTests=ON
fi

shift

if [ "`uname -s`" = "Linux" ]; then
    compilers="-DCMAKE_C_COMPILER=/usr/bin/gcc-4.9 -DCMAKE_CXX_COMPILER=/usr/bin/g++-4.9"
else
    compilers=""
fi

if [ "`hash ninja 2>&1`" = "" ]; then
    ninjaFound=true
    generator="Ninja"
    cmakeGenerator="Ninja"
else
    ninjaFound=false
    generator="Make"
    cmakeGenerator="Unix Makefiles"
fi

if [ "$cmakeBuildType" = "Release" ]; then
    titleTests=""
else
    titleTests=" and its tests"
fi

echo "\033[44;37;1mMaking OpenCOR$titleTests (using $generator)...\033[0m"

cd build

cmake -G "$cmakeGenerator" $compilers -DCMAKE_BUILD_TYPE=$cmakeBuildType -DENABLE_TESTS=$enableTests ..

exitCode=$?

if [ $exitCode -ne 0 ]; then
    cd ..

    exit $exitCode
fi

if [ $ninjaFound = true ]; then
    ninja
else
    make $*
fi

exitCode=$?

cd ..

if [ $exitCode -eq 0 ]; then
    echo "\033[42;37;1mAll done!\033[0m"
fi

exit $exitCode
