#!/bin/bash

appDir=$(cd $(dirname $0); pwd)/..

if [ -d $appDir/build ]; then
    if [ "$1" = "Release" ]; then
        cmakeBuildType=Release
        enableTests=OFF
    elif [ "$1" = "Tests" ]; then
        cmakeBuildType=Debug
        enableTests=ON
    else
        echo "Only the Release and Tests options are supported."

        exit 1
    fi

    if [ "`hash ninja 2>&1`" = "" ]; then
        ninjaFound=true
        generator="Ninja"
        cmakeGenerator="Ninja"
    else
        ninjaFound=false
        generator="Make"
        cmakeGenerator="Unix Makefiles"
    fi

    if [ "$1" = "Debug" ]; then
        extraTitleInfo=" for testing"
    fi

    echo -e "\033[44;37;1mBuilding OpenCOR$extraTitleInfo using $generator...\033[0m"

    origDir=`pwd`

    cd $appDir/build

    cmake -G "$cmakeGenerator" -DCMAKE_BUILD_TYPE=$cmakeBuildType -DENABLE_TESTS=$enableTests ..

    exitCode=$?

    if [ $exitCode -ne 0 ]; then
        cd $origDir

        exit $exitCode
    fi

    shift

    if [ $ninjaFound = true ]; then
        ninja $@
    else
        make $@
    fi

    exitCode=$?

    cd $origDir

    if [ $exitCode -eq 0 ]; then
        echo -e "\033[42;37;1mAll done!\033[0m"
    fi

    exit $exitCode
else
    echo "OpenCOR's build directory is missing."

    exit 1
fi
