#!/bin/sh

if [ "$1" = "all" ]; then
    echo "\033[44;37;1mCleaning all of OpenCOR...\033[0m"
else
    echo "\033[44;37;1mCleaning OpenCOR...\033[0m"
fi

rm -fr build/.clang-tidy build/.ninja* build/* > /dev/null 2>&1

if [ "$1" = "all" ]; then
    extPath=ext
else
    extPath=ext/doc
fi

rm -fr $extPath/* > /dev/null 2>&1

echo "\033[42;37;1mAll done!\033[0m"
