#!/bin/sh

if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
    # Clone OpenCOR

    if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then
        docker exec -ti travis-ci bash -c "   git clone --depth=50 --branch=master https://github.com/opencor/opencor.git opencor \
                                           && cd opencor \
                                           && git checkout -qf ${TRAVIS_COMMIT}"
    else
        docker exec -ti travis-ci bash -c "   git clone --depth=50 https://github.com/opencor/opencor.git opencor \
                                           && cd opencor \
                                           && git fetch origin +refs/pull/${TRAVIS_PULL_REQUEST}/merge \
                                           && git checkout -qf FETCH_HEAD"
    fi

    if [ $? = 0 ]; then
        # Note: on Linux, the linking of CellMLTextView_conversiontests and
        #       CellMLTextView_parsingtests results in an error regarding
        #       __cxa_throw_bad_array_new_length@Qt_5 not being defined in
        #       libqscintilla2_qt5.so.13. This is most likely related to our use
        #       of GCC/G++ 5.x. However, a simple workaround is to build
        #       QScintilla, so this is what we are doing here...

        docker exec -ti travis-ci bash -c "   export CONFIG=${CONFIG} \
                                           && export CC=gcc \
                                           && export CXX=g++ \
                                           && g++ --version \
                                           && cd opencor/build \
                                           && cmake -G Ninja -DCMAKE_BUILD_TYPE=$CONFIG -DENABLE_TRAVIS_CI=ON -DCMAKE_PREFIX_PATH=/opt/qt56/lib/cmake -DUSE_PREBUILT_QSCINTILLA_PACKAGE=OFF -DENABLE_SAMPLE_PLUGINS=ON -DENABLE_TEST_PLUGINS=ON -DENABLE_TESTS=ON .. \
                                           && ninja \
                                           && bin/runtests"
    fi
else
       cd build \
    && cmake -G Ninja -DCMAKE_BUILD_TYPE=$CONFIG -DENABLE_TRAVIS_CI=ON -DCMAKE_PREFIX_PATH=/usr/local/opt/qt5/lib/cmake -DENABLE_SAMPLE_PLUGINS=ON -DENABLE_TEST_PLUGINS=ON -DENABLE_TESTS=ON .. \
    && ninja \
    && OpenCOR.app/Contents/MacOS/runtests
fi
