#!/bin/sh

if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
    echo "TRAVIS_BUILD_DIR -- ${TRAVIS_BUILD_DIR}"
    echo "TRAVIS_BUILD_ID -- ${TRAVIS_BUILD_ID}"
    echo "TRAVIS_BUILD_NUMBER -- ${TRAVIS_BUILD_NUMBER}"
    echo "TRAVIS_COMMIT -- ${TRAVIS_COMMIT}"
    echo "TRAVIS_COMMIT_MESSAGE -- ${TRAVIS_COMMIT_MESSAGE}"
    echo "TRAVIS_COMMIT_RANGE -- ${TRAVIS_COMMIT_RANGE}"
    echo "TRAVIS_EVENT_TYPE -- ${TRAVIS_EVENT_TYPE}"
    echo "TRAVIS_JOB_ID -- ${TRAVIS_JOB_ID}"
    echo "TRAVIS_JOB_NUMBER -- ${TRAVIS_JOB_NUMBER}"
    echo "TRAVIS_OS_NAME -- ${TRAVIS_OS_NAME}"
    echo "TRAVIS_PULL_REQUEST -- ${TRAVIS_PULL_REQUEST}"
    echo "TRAVIS_PULL_REQUEST_BRANCH -- ${TRAVIS_PULL_REQUEST_BRANCH}"
    echo "TRAVIS_PULL_REQUEST_SHA -- ${TRAVIS_PULL_REQUEST_SHA}"
    echo "TRAVIS_PULL_REQUEST_SLUG -- ${TRAVIS_PULL_REQUEST_SLUG}"
    echo "TRAVIS_REPO_SLUG -- ${TRAVIS_REPO_SLUG}"
    echo "TRAVIS_SECURE_ENV_VARS -- ${TRAVIS_SECURE_ENV_VARS}"
    echo "TRAVIS_SUDO -- ${TRAVIS_SUDO}"
    echo "TRAVIS_TEST_RESULT -- ${TRAVIS_TEST_RESULT}"
    echo "TRAVIS_TAG -- ${TRAVIS_TAG}"

    if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then
        docker exec -ti travis-ci bash -c "git clone --depth=50 --branch=master https://github.com/opencor/opencor.git opencor; \
                                           cd opencor; \
                                           git checkout -qf ${TRAVIS_COMMIT}"
    else
        docker exec -ti travis-ci bash -c "git clone --depth=50 https://github.com/opencor/opencor.git opencor; \
                                           cd opencor; \
                                           git fetch origin +refs/pull/${TRAVIS_PULL_REQUEST}/merge; \
                                           git checkout -qf FETCH_HEAD"
    fi
    
    docker exec -ti travis-ci bash -c "export CONFIG=${CONFIG}; \
                                       export CC=gcc; \
                                       export CXX=g++; \
                                       g++ --version; \
                                       cd opencor/build; \
                                       cmake -G Ninja -DCMAKE_BUILD_TYPE=$CONFIG -DENABLE_TRAVIS_CI=ON -DCMAKE_PREFIX_PATH=/opt/qt56/lib/cmake -DENABLE_SAMPLE_PLUGINS=ON -DENABLE_TEST_PLUGINS=ON -DENABLE_TESTS=ON ..; \
                                       ninja; \
                                       bin/runtests"
else
    cd build
    cmake -G Ninja -DCMAKE_BUILD_TYPE=$CONFIG -DENABLE_TRAVIS_CI=ON -DCMAKE_PREFIX_PATH=/usr/local/opt/qt5/lib/cmake -DENABLE_SAMPLE_PLUGINS=ON -DENABLE_TEST_PLUGINS=ON -DENABLE_TESTS=ON ..
    ninja
    OpenCOR.app/Contents/MacOS/runtests
fi
