#!/bin/sh

if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
    docker pull ubuntu:16.04
    docker run --name travis-ci -v $TRAVIS_BUILD_DIR:/iqrfsdk -td ubuntu:16.04 /bin/bash
    docker exec -ti travis-ci bash -c "apt -y --force-yes -qq update; \
                                       apt -y --force-yes install software-properties-common; \
                                       apt-add-repository -y ppa:beineri/opt-qt562-xenial; \
                                       apt -y --force-yes -qq update; \
                                       apt -y --force-yes -qq install cmake g++-5 git libgl1-mesa-dev libglu1-mesa-dev ninja-build; \
                                       apt -y --force-yes -qq install qt56location qt56multimedia qt56sensors qt56svg qt56tools qt56webchannel; \
                                       echo "ln -s /usr/g++-5 /usr/g++:"; \
                                       ln -s /usr/g++-5 /usr/g++; \
                                       echo "which g++:"; \
                                       which g++; \
                                       echo "PATH:"; \
                                       echo $PATH; \
                                       echo "/usr/bin:"; \
                                       ls -al /usr/bin; \
                                       echo "/usr/local:"; \
                                       ls -al /usr/local; \
                                       echo "/usr/local/bin:"; \
                                       ls -al /usr/local/bin; \
                                       /usr/bin/g++ --version"
else
    brew update
    curl -O https://raw.githubusercontent.com/Homebrew/homebrew-core/106d0878ee812cb8f5c403f717bdebe836445aee/Formula/qt5.rb
    brew install ./qt5.rb ninja
    export OPENSSL_ROOT_DIR=/usr/local/opt/openssl
    chmod -R 755 /usr/local/opt/qt5/*
fi
