#!/bin/sh

# Note: the linking of CellMLTextView_conversiontests and
#       CellMLTextView_parsingtests results in an error regarding
#       __cxa_throw_bad_array_new_length@Qt_5 not being defined in
#       libqscintilla2_qt5.so.13. This is most likely related to our use of
#       GCC/G++ 5.x. However, a simple workaround is to build QScintilla, so
#       this is what we are doing here...

   cd /opencor/build \
&& ls -al
&& cmake -G Ninja -DCMAKE_BUILD_TYPE=$CONFIG -DENABLE_TRAVIS_CI=ON -DCMAKE_PREFIX_PATH=/opt/qt56/lib/cmake -DUSE_PREBUILT_QSCINTILLA_PACKAGE=OFF -DENABLE_SAMPLE_PLUGINS=ON -DENABLE_TEST_PLUGINS=ON -DENABLE_TESTS=ON .. \
&& ninja \
&& /opencor/bin/runtests
