#!/bin/bash

set -e

appDir=$(cd $(dirname $0); pwd)/../../build/OpenCOR.app
appExe=$appDir/Contents/MacOS/OpenCOR

if [ -f $appExe ]; then
    codesign --deep --force --options runtime --sign "$DEVELOPER_ID_APPLICATION_CERTIFICATE_DESCRIPTION" --strict --timestamp $appDir

    exitCode=$?

    if [ $exitCode -ne 0 ]; then
        exit $exitCode
    fi

    ditto -c -k --keepParent $appDir $appDir.zip

    xcrun notarytool submit $appDir.zip --apple-id $APPLE_ID --password $APPLE_APP_SPECIFIC_PASSWORD --team-id $APPLE_TEAM_ID --wait

    exitCode=$?

    if [ $exitCode -ne 0 ]; then
        exit $exitCode
    fi

    xcrun stapler staple $appDir

    exit $?
else
    echo "OpenCOR must first be built before being code signed."

    exit 1
fi
